### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@banesullivan forgot to mention that I am looking using templates for issues. Let me know if you or @mcovalt has any thoughts. Low priority, we can discuss next week if needed.

**Comment by banesullivan** [comment]
@aashish24, LGTM though is the intent of this to use this repo as a catch-all place for bug reporting and feature requests? If so, I will need to do some additional work to make sure the repo is set up to handle that (i.e., labels and automations with he project board)

**Comment by aashish24** [comment]
> @aashish24, LGTM though is the intent of this to use this repo as a catch-all place for bug reporting and feature requests? If so, I will need to do some additional work to make sure the repo is set up to handle that (i.e., labels and automations with he project board)

labels and automations with the project board would be nice. Do you setup that in the GitHub setting somewhere?

**Comment by aashish24** [comment]
Since we are not using the template we could close this issue

**Pull request closed without merging**
